spring.application.name=streamversex-backend

server.port=8080
#spring.mongodb.uri=mongodb://localhost:27017/streamversex
#spring.devtools.restart.enabled=false
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=streamversex

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ypardeshi561@gmail.com
spring.mail.password=zdohyuuyyrqoizym
spring.mail.properties.mail.smtp.auth=true
app.base-url=http://localhost:8080
#app.frontend-url=http://localhost:5173
spring.mail.properties.mail.smtp.starttls.enable=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#jwt.secret=${JWT_SECRET:change-this-to-a-long-random-secret-before-deploying}
#jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
jwt.secret=VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yU3RyZWFtVmVyc2VYMjAyNg==
jwt.expiration-ms=86400000
# TMDB
tmdb.base-url=https://api.themoviedb.org/3
tmdb.access-token=${TMDB_ACCESS_TOKEN}

omdb.api-key=${OMDB_API_KEY:}
omdb.base-url=https://www.omdbapi.com

gemini.api-key=${GEMINI_API_KEY:}

razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

logging.level.com.streamversex.backend=DEBUG